### PR TITLE
Add in-memory file uploads

### PR DESCRIPTION
**Pull request by asonix**
I went ahead an implemented this (fixing https://github.com/ferristseng/rust-hyper-multipart-rfc7578/issues/1). I have tested it in the [telebot-hyper](https://github.com/asonix/telecord/tree/telebot-hyper) branch of my Telecord project.

### CODE REVIEW

**Comment by asonix** [comment]
Hey, not to push you or anything, but it would be super cool if you could look at this pull request

**Comment by asonix** [comment]
I've rebased these changes on your latest commits. Could you please take a look at them?

**Comment by ferristseng** [comment]
Sorry, I wasn't getting notified about these. I will take a look at this soon, thanks!

**Comment by ferristseng** [comment]
@asonix Hey, this looks good. Can you revert the changes you made to the Cargo.toml file though?

Thanks, and sorry it took so long for me to review this.

**Pull request merged**
